### ISSUE TITLE
About 'DTWeakSupport.h' file not found

### ISSUE THREAD

**Issue by JasonLiuOrg** [ianyh/Highball#145]
When I run this project, there is an issue ''DTWeakSupport.h' file not found' .

**Comment by giaotuancse** [comment]
use `#import <DTFoundation/DTWeakSupport.h>` instead

**Comment by ianyh** [comment]
Yes. It was a bug in `DTCoreText` that used the wrong import reference which breaks when being used as a framework via CocoaPods. I think it has since been fixed but I haven't updated the pods recently.

**Comment by JasonLiuOrg** [comment]
When can you update your recent pods? Your project is a good example of learning how to use swift to develop ios apps. @ianyh
